include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error

linter:
  rules:
    prefer_const_constructors: false
    prefer_relative_imports: true
    constant_identifier_names: false
    prefer_const_declarations: false